// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5536.titan2017;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.Relay;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Ultrasonic;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.ADXRS450_Gyro;
import edu.wpi.first.wpilibj.BuiltInAccelerometer;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveTrainleftFront;
    public static CANTalon driveTrainleftRear;
    public static CANTalon driveTrainrightFront;
    public static CANTalon driveTrainrightRear;
    public static RobotDrive driveTrainmecanumDrive;
    public static Ultrasonic driveTrainfrontUltrasonic;
    public static Ultrasonic driveTrainrearUltrasonic;
    public static Compressor clawcompressor;
    public static Solenoid clawliftSolenoid;
    public static Solenoid clawgripSolenoid;
    public static SpeedController climberleftMotor;
    public static SpeedController climberrightMotor;
    public static SpeedController shootershootMotor;
    public static SpeedController feederfeederMotor;
    public static Servo cameraMountxServo;
    public static Servo cameraMountyServo;
    public static Relay targetingLightlightOnRelay;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static ADXRS450_Gyro driveTrainGyro;
    public static BuiltInAccelerometer driveTrainaccelerometer;

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainleftFront = new CANTalon(2);
        LiveWindow.addActuator("driveTrain", "leftFront", driveTrainleftFront);
        
        driveTrainleftRear = new CANTalon(3);
        LiveWindow.addActuator("driveTrain", "leftRear", driveTrainleftRear);
        
        driveTrainrightFront = new CANTalon(0);
        LiveWindow.addActuator("driveTrain", "rightFront", driveTrainrightFront);
        
        driveTrainrightRear = new CANTalon(1);
        LiveWindow.addActuator("driveTrain", "rightRear", driveTrainrightRear);
        
        driveTrainmecanumDrive = new RobotDrive(driveTrainleftFront, driveTrainleftRear,
              driveTrainrightFront, driveTrainrightRear);
        
        driveTrainmecanumDrive.setSafetyEnabled(true);
        driveTrainmecanumDrive.setExpiration(0.1);
        driveTrainmecanumDrive.setSensitivity(0.5);
        driveTrainmecanumDrive.setMaxOutput(1.0);

        driveTrainmecanumDrive.setInvertedMotor(RobotDrive.MotorType.kFrontRight, true);
        driveTrainmecanumDrive.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);
        driveTrainfrontUltrasonic = new Ultrasonic(0, 1);
        LiveWindow.addSensor("driveTrain", "frontUltrasonic", driveTrainfrontUltrasonic);
        
        driveTrainrearUltrasonic = new Ultrasonic(2, 3);
        LiveWindow.addSensor("driveTrain", "rearUltrasonic", driveTrainrearUltrasonic);
        
        clawcompressor = new Compressor(0);
        
        
        clawliftSolenoid = new Solenoid(0, 0);
        LiveWindow.addActuator("claw", "liftSolenoid", clawliftSolenoid);
        
        clawgripSolenoid = new Solenoid(0, 1);
        LiveWindow.addActuator("claw", "gripSolenoid", clawgripSolenoid);
        
        climberleftMotor = new Spark(0);
        LiveWindow.addActuator("climber", "leftMotor", (Spark) climberleftMotor);
        
        climberrightMotor = new Spark(1);
        LiveWindow.addActuator("climber", "rightMotor", (Spark) climberrightMotor);
        
        shootershootMotor = new Spark(2);
        LiveWindow.addActuator("shooter", "shootMotor", (Spark) shootershootMotor);
        
        feederfeederMotor = new Spark(3);
        LiveWindow.addActuator("feeder", "feederMotor", (Spark) feederfeederMotor);
        
        cameraMountxServo = new Servo(4);
        LiveWindow.addActuator("cameraMount", "xServo", cameraMountxServo);
        
        cameraMountyServo = new Servo(5);
        LiveWindow.addActuator("cameraMount", "yServo", cameraMountyServo);
        
        targetingLightlightOnRelay = new Relay(0);
        LiveWindow.addActuator("targetingLight", "lightOnRelay", targetingLightlightOnRelay);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        
        driveTrainGyro = new ADXRS450_Gyro();
        driveTrainaccelerometer = new BuiltInAccelerometer();
        
        driveTrainfrontUltrasonic.setAutomaticMode(true);
        driveTrainrearUltrasonic.setAutomaticMode(true);
    }
}
